# Site wide configuration


title: Cooper Laboratory
description: "evolution-in-action at University of Pittsburgh School of Medicine"
logo: sm-wrinkly.gif # 120x120 px default image used for Twitter summary card
teaser: burk-fm.gif # 400x250 px default teaser image used in image archive grid
locale: en
url:

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:
owner: Vaughn Cooper
name: Vaughn Cooper
email: vscooper@gmail.com
# twitter: @vscooper
#  google:
#    ad-client:
#    ad-slot:
#  bio:
#  avatar: bio-photo.jpg # 160x160 px image for author byline
#  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
